apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  volumes:  #containers volume name its creation
    - name: mypod
      persistentVolumeClaim:    #name of pvc that will be attached to your pod
        claimName: pv-claim  #nameo of pvc
  containers:
    - name: mycontainer
      image: nginx
      volumeMounts:     #
      - mountPath: "/share/local/nginx/"  #the source location from where data will be captured by pvc
        name: mypod
      ports:
       - containerPort: 80
         protocol: TCP