apiVersion: v1
kind: PersistentVolume
metadata: 
   name: pv-volume
   labels:
     type: pv
spec:
    storageClassName: standard
    volumeMode: Filesystem
    capacity:
       storage: 10Gi
       accessModes:
          - ReadWriteOnce
       persistentVolumeReclaimPolicy: Retain
       hostPath:
        path: "/mnt/data"
           

